; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; PlatformIO Project Configuration File for ESP32
[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps = 
    madhephaestus/ESP32Servo@^1.2.1
    hideakitai/MPU9250 @ ^0.4.8
    https://github.com/me-no-dev/ESPAsyncWebServer.git
    https://github.com/me-no-dev/AsyncTCP.git
monitor_speed = 115200
upload_protocol = espota
upload_port = 192.168.0.63  ; Put your ESP32's IP address here
board_build.filesystem = littlefs